Chart inherit widget
beeware/toga-chart pull request #22
Opened 2022-09-19 10:06 UTC by saroad2

Fixes #21 

Chart now inherits `toga.Widget` directly instead of `Canvas`.

Moreover, renamed the internal `Chart._resize` method to `Chart.redraw`. Now users can redraw the chart manually when needed.

## PR Checklist:

- [X] All new features have been tested
- [X] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2022-09-28 00:15 UTC, freakboy3742 requested changes
The general direction on this looks good; but it appears to be incomplete. On macOS, the chart doesn't render on first load, and it doesn't re-render on resize.

2022-09-28 08:26 UTC, saroad2 commented
I don't have access to a Mac machine, so I cannot validate this, but I think that 2 small changes can ix the problem:

first, in the constructor of `Chart` we should set the `on_draw` attribute before setting up the canvas constructor. So now the constructor should look like:

```python
    def __init__(self, id=None, style=None, on_resize=None, on_draw=None, factory=None):
        if on_resize is None:
            on_resize = self.redraw
        self.on_draw = on_draw
        super().__init__(id=id, style=style, factory=factory)
        self.canvas = Canvas(style=style, on_resize=on_resize, factory=factory)
        self._impl = self.canvas._impl
```

Seconds, cocoa implementation of `on_resize` requires that the widget will have a winodw. I suspect that the window is set for the `Chart` but not for the `Canvas`. We can solve this by overloading the `Chart._set_window` method and set the window to the canvas as well. This should look like:

```python
    def _set_window(self, window):
        self.canvas.window = window
```

Both changes should fix the problem. However, the second fix reveals a greater problem with the `Widget` class: The `window` attribute is saved in the **interface layer** as an inner attribute `_window`, while the actual setting of the window happens in the **implementation layer** via the `set_window` method. It seems like that in the same way that there is a `set_window` method in the implentation layer, there should also be `get_window` method. In that way, the source of truth of which is the window of the widget is only set in the implementation layer and not the interface layer.

2022-10-24 03:58 UTC, saroad2 commented
Hey @freakboy3742 ,
I would love to get your feedback on this PR, once you have the time. I need it for Eddington.

Thanks!

2022-10-27 06:44 UTC, freakboy3742 approved these changes
The changes you suggested were enough for macOS; one more change was needed to get the chart working on GTK (proxying the layout attribute).

The layout change in particular reinforces the point you made about layer crossing - there's definitely room for improvement here. My immediate impression is that what we need is a true concept of a "composite" widget, rather than faking one by redirecting the impl of Chart to Canvas; making that change work will also necessitate cleaning up some of the layer crossing that you refered to.

However, those changes (a) will depend on changes upstream in Toga, and (b) should be entirely internal changes to Toga-chart, once they're made. The major improvement of this PR is decoupling the API of Chart from Canvas; while the way that decoupling is implemeted may change, the public API of the Chart widget is now "clean" (in that it doesn't expose any inherited APIs from Canvas). We're now free to modify the implementation of Chart as needed without impacting the public usage of toga-chart.

2022-10-27 06:44 UTC, merged